server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.239.128
    username: admin
    password: admin
    virtual-host: /
  redis:
    host: 192.168.239.128
ly:
  sms:
    accessKeyId: LTAIfBy2qBIH4ct0
    accessKeySecret: gtV32ZyTtzTnHzaAZq5Hi06V4TUHD5
    signName: 乐优商城
    verifyCodeTemplate: SMS_170842810